import { useEffect, useState } from 'react';
import { token } from './AuthGate';
const API = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000';
const headers = () => ({ Authorization: `Bearer ${token() ?? ''}` });
export default function AdminPanel() {
  const [dashboard,setDashboard]=useState<any>(null),[users,setUsers]=useState<any[]>([]),[simulations,setSimulations]=useState<any[]>([]),[logs,setLogs]=useState<any[]>([]),[keywords,setKeywords]=useState<any[]>([]),[newKeyword,setNewKeyword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{const h=headers();const [me,d,u,s,l,k]=await Promise.all(['/auth/me','/admin/dashboard','/admin/users','/admin/simulations','/admin/ai-logs','/admin/keywords'].map(p=>fetch(`${API}${p}`,{headers:h})));if(!me.ok){setDashboard({hidden:true});return;}const profile=await me.json();if(profile.role!=='ADMIN'){setDashboard({hidden:true});return;}if(![d,u,s,l,k].every(r=>r.ok))throw new Error('관리자 데이터를 불러오지 못했습니다.');setDashboard(await d.json());setUsers(await u.json());setSimulations(await s.json());setLogs(await l.json());setKeywords(await k.json());}catch(e){setError(e instanceof Error?e.message:'오류가 발생했습니다.')}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const role=async(id:number,current:string)=>{const next=current==='ADMIN'?'USER':'ADMIN';if(!confirm(`${next} 권한으로 변경할까요?`))return;const r=await fetch(`${API}/admin/users/${id}/role`,{method:'PATCH',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({role:next})});if(!r.ok){const d=await r.json();alert(d.detail??'역할 변경 실패');return}load()};
  const removeSimulation=async(id:number)=>{if(!confirm('이 시뮬레이션을 삭제할까요?'))return;await fetch(`${API}/admin/simulations/${id}`,{method:'DELETE',headers:headers()});load()};
  const addKeyword=async()=>{if(!newKeyword.trim())return;const r=await fetch(`${API}/admin/keywords`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({value:newKeyword})});if(!r.ok){const d=await r.json();alert(d.detail??'키워드 추가 실패');return}setNewKeyword('');load()};
  const editKeyword=async(k:any)=>{const value=prompt('키워드 수정',k.value);if(!value?.trim())return;const r=await fetch(`${API}/admin/keywords/${k.id}`,{method:'PATCH',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({value})});if(!r.ok){const d=await r.json();alert(d.detail??'키워드 수정 실패');return}load()};
  const deleteKeyword=async(id:number)=>{if(!confirm('키워드를 삭제할까요?'))return;await fetch(`${API}/admin/keywords/${id}`,{method:'DELETE',headers:headers()});load()};
  if(loading)return <section className="panel"><p>관리자 데이터를 불러오는 중...</p></section>; if(dashboard?.hidden)return null; if(error)return <section className="panel"><h2>관리자 영역</h2><p className="error-message">{error}</p></section>;
  return <section className="panel admin-panel"><h1>관리자 대시보드</h1><div className="admin-stats"><div>사용자<strong>{dashboard.users}</strong></div><div>시뮬레이션<strong>{dashboard.simulations}</strong></div><div>성공<strong>{dashboard.status_counts?.succeeded??0}</strong></div><div>실패<strong>{dashboard.status_counts?.failed??0}</strong></div></div><h2>사용자 관리</h2><div className="admin-table">{users.map(u=><div className="admin-row" key={u.id}><span>#{u.id} {u.email}</span><span>{u.role}</span><span>시뮬레이션 {u.simulation_count}개</span><button onClick={()=>role(u.id,u.role)}>권한 변경</button></div>)}</div><h2>전체 시뮬레이션 관리</h2><div className="admin-table">{simulations.length?simulations.map(s=><div className="admin-row" key={s.id}><span>#{s.id} {s.product_name}</span><span>{s.status}</span><span>사용자 #{s.user_id??'익명'}</span><button onClick={()=>removeSimulation(s.id)}>삭제</button></div>):<p>저장된 시뮬레이션이 없습니다.</p>}</div><h2>AI 사용량 로그</h2><div className="admin-table">{logs.length?logs.map(l=><div className="admin-row" key={l.id}><span>시뮬레이션 #{l.simulation_id}</span><span>{l.model_name}</span><span>{l.total_tokens??0} tokens</span><span>{l.estimated_cost??'-'}</span></div>):<p>AI 사용량 로그가 없습니다.</p>}</div><h2>키워드 관리</h2><div><input value={newKeyword} onChange={e=>setNewKeyword(e.target.value)} placeholder="새 키워드"/><button onClick={addKeyword}>추가</button></div><div className="keyword-list">{keywords.map(k=><span className="keyword-chip" key={k.id}>{k.value}<button onClick={()=>editKeyword(k)}>수정</button><button onClick={()=>deleteKeyword(k.id)}>삭제</button></span>)}</div></section>;
}
