import { useEffect, useState } from 'react';
const API = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000';
export function token() { return localStorage.getItem('access_token'); }
export default function AuthGate({ children }: { children: React.ReactNode }) {
  const queryToken = new URLSearchParams(window.location.search).get('access_token'); if (queryToken) { localStorage.setItem('access_token', queryToken); window.history.replaceState({}, '', '/'); }
  const [loggedIn, setLoggedIn] = useState(Boolean(token())); const [signup, setSignup] = useState(false);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (!token()) return; fetch(`${API}/auth/me`, { headers: { Authorization: `Bearer ${token()}` } }).then((response) => { if (!response.ok) { localStorage.removeItem('access_token'); setLoggedIn(false); } }).catch(() => { /* retain session during temporary backend restart */ }); }, []);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); try { const response = await fetch(`${API}/auth/${signup ? 'signup' : 'login'}`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({email,password}) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? '요청에 실패했습니다.'); if (signup) { setSignup(false); setError('회원가입이 완료되었습니다. 로그인해주세요.'); } else { localStorage.setItem('access_token', data.access_token); setLoggedIn(true); } } catch (e) { setError(e instanceof Error ? e.message : '요청에 실패했습니다.'); } };
  if (!loggedIn) return <main className="auth-page"><section className="auth-visual"><div className="auth-brand"><span>◈</span><strong>FocusGroup</strong></div><div className="auth-copy"><span className="auth-kicker">AI RESEARCH STUDIO</span><h1>더 빠르게 이해하고,<br /><em>더 자신 있게</em> 결정하세요.</h1><p>AI 가상 소비자 패널이 제품과 광고 문구를 분석하고, 실행 가능한 인사이트를 제공합니다.</p><div className="auth-points"><span>✦</span> 10명의 가상 소비자 패널<div /><span>◌</span> 데이터 기반 인사이트</div></div><div className="auth-glow" /></section><section className="auth-card"><div className="auth-card-header"><span className="auth-kicker">WELCOME BACK</span><h2>{signup ? '계정 만들기' : '다시 만나서 반가워요'}</h2><p>{signup ? '새로운 인사이트 여정을 시작하세요.' : '워크스페이스에 로그인하세요.'}</p></div><form onSubmit={submit}><label>이메일<input type="email" placeholder="you@company.com" value={email} onChange={(e)=>setEmail(e.target.value)} required /></label><label>비밀번호<input type="password" placeholder="8자 이상 입력" value={password} onChange={(e)=>setPassword(e.target.value)} required minLength={8} /></label><button className="auth-primary" type="submit">{signup ? '계정 만들기' : '로그인'} <span>→</span></button></form>{!signup && <><div className="auth-divider"><span>또는</span></div><button className="auth-google" onClick={()=>window.location.href=`${API}/auth/google`}><b>G</b> Google로 계속하기</button></>}{error && <p className="error-message">{error}</p>}<p className="auth-switch">{signup ? '이미 계정이 있나요?' : '아직 계정이 없나요?'} <button onClick={()=>{setSignup(!signup);setError('')}}>{signup ? '로그인' : '회원가입'}</button></p><small className="auth-terms">계속 진행하면 서비스 이용약관과 개인정보 처리방침에 동의하는 것으로 간주됩니다.</small></section></main>;
  return <>{children}<button className="logout-button" onClick={()=>{localStorage.removeItem('access_token');setLoggedIn(false);}}>로그아웃</button></>;
}
